version: '3.8'

services:
  db:
    image: postgres:16
    container_name: urbanodb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urbano
    ports:
      - "5432:5432"

  app:
    env_file:
      - .env
    build: .
    container_name: urbano
    ports:
      - "8080:8080"
    depends_on:
      - db
